//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace View
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputView
	{
	    public InputView()
	    {
	        
	    }

	    public int AskPlayerAmmount()
	    {
	        Console.WriteLine("How many players?");
	        return Convert.ToInt32(Console.ReadLine());
	    }

	    public string AskPlayerName()
        {
            Console.WriteLine("What will be your player name?");
            return Console.ReadLine();
        }
	}
}
