//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace View
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OutputView
	{

	    public void ShowBoard(Field[,] fields)
	    {
            Console.WriteLine("");
            for (int y = 0; y < 15; y++) 
	        {
                for (int x = 0; x < 23; x++)
                {
                    Field field = fields[y, x];
                    if (field == null)
                    {
                        Console.Write("  ");
                    }
                    else if (field.Barricade != null)
                    {
                        Console.Write(field.Barricade.Icon);
                    }
                    else if (field.Pawn != null)
                    {
                        Console.Write(field.Pawn.Icon);
                    }
                    else
	                    Console.Write(fields[y,x].Icon);
	            }
                Console.WriteLine();
            }
            Console.WriteLine();
        }

        public void ShowThrow(int eyes)
	    {
	        Console.WriteLine("Moves Left: " + eyes);
	    }

	    public void WrongDirection()
	    {
	        Console.WriteLine("Wrong Direction");
	    }

	    public void ShowPlayer(Player gameCurrentPlayer)
	    {
	        Console.WriteLine("The Current Player = " + gameCurrentPlayer.Name);
            Console.WriteLine("color = " + gameCurrentPlayer.Color.ToString());
	    }

	    public void ClearConsole()
	    {
	        Console.Clear();
	    }
	}
}

