//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class Controller
	{
	    public virtual Dice Dice { get; set; }

	    public virtual InputView InputView { get; set; }

	    public virtual OutputView OutputView { get; set; }

	    public virtual Game Game { get; set; }

	    public Controller()
	    {
            Game = new Game();
	        SetupGame();   
	    }

        public void SetupGame()
        {
            var Player = new List<Player>();
            var color = new Color[4] { Color.Blue, Color.Green, Color.Red, Color.Yellow };
            int playerAmmount = InputView.AskPlayerAmmount();
            for (int i = 0; i < playerAmmount; i++)
            {
                Game.SetPlayers(new Player { Name = InputView.AskPlayerName(), Color = color[i] });
            }

            buildFields();
        }

        public virtual void GameRunning()
        {
            throw new System.NotImplementedException();
        }


        private void buildFields()
        {
            
        }
    }
}

