//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Board
{
    public virtual List<Field> Field { get; set; }

    public Board()
    {
        for (int i = 0; i < 61; i++)
        {
            Field.Add(new Field());
        }
    }
}

