//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Dice
	{
		public virtual int Throw()
		{
			throw new System.NotImplementedException();
		}

        public virtual int eyes
        {
            get;
            set;
        }

        public virtual Game Game
        {
            get;
            set;
        }

    }
}

