//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Text;

public class Pawn
{
    public int LocationX { get; set; }

    public int LocationY { get; set; }

    public int Id { get; set; }

    public string Icon { get; set; }

    public Player Owner { get; set; }
}

