//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
    public virtual IEnumerable<Pawn> Pawn { get; set; }

    public virtual Color Color { get; set; }

    public virtual IEnumerable<StartField> StartField { get; set; }

    public Player()
    {
        
    }

    public void Move()
    {
        throw new NotImplementedException();
    }

}

