//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
    public virtual List<Pawn> Pawn { get; set; }

    public virtual Color Color { get; set; }

    public string Name { get; set; }

    public virtual IEnumerable<StartField> StartField { get; set; }

    public Player()
    {
        Pawn = new List<Pawn> { 
            new Pawn{id = 1},
            new Pawn{id = 2},
            new Pawn{id = 3},
            new Pawn{id = 4}};
    }

    public void Move()
    {
        throw new NotImplementedException();
    }

}

